
## TERCER MODULO - PAO25_25_07_Python_Pandas

*Andres Aguiar*

### 1 Pandas

* Librería (de facto estándar) para estructurar datos tabulares
* Multivariable (string, int, float, bool…)
* Dos clases:– Series (1 dimensión)– DataFrames (2+ dimensiones

In [2]:
 # librería externa
import pandas as pd
from pandas import Series, DataFrame

In [3]:
pd.__version__

'2.3.3'

### 2 Series

* Datos unidimensionales (similar a NumPy)
* Elementos + índices modificables

In [4]:
countries = pd.Series(['Spain','Andorra','Gibraltar','Portugal','France'])
print(countries)

0        Spain
1      Andorra
2    Gibraltar
3     Portugal
4       France
dtype: object

In [5]:
# especificando el índice
countries = pd.Series(['Spain','Andorra','Gibraltar','Portugal','France'],
index=range(10,60,10))
print(countries)

10        Spain
20      Andorra
30    Gibraltar
40     Portugal
50       France
dtype: object

In [6]:
# los índices pueden ser de más tipos
football_cities = pd.Series(['Barcelona','Madrid','Valencia','Sevilla'],
index=['a','b','c','d'])
print(football_cities)

a    Barcelona
b       Madrid
c     Valencia
d      Sevilla
dtype: object

In [7]:
# Atributos
football_cities.name = 'Ciudades con dos equipos en primera' # nombrar la Serie
football_cities.index.name = 'Id' # Describir los índices
print(football_cities)

Id
a    Barcelona
b       Madrid
c     Valencia
d      Sevilla
Name: Ciudades con dos equipos en primera, dtype: object

In [10]:
# acceso similar a NumPy o listas, según posición (depecrated)
print(football_cities.iloc[2])
# acceso a través del índice semántico
print(football_cities['c'])
print(football_cities['c'] == football_cities.iloc[2])

Valencia
Valencia
True

### 3 Tratamiento similar a ndarray

In [12]:
# múltiple recolección de elementos
print(football_cities[['a','c']])
print(football_cities.iloc[[0,3]])

Id
a    Barcelona
c     Valencia
Name: Ciudades con dos equipos en primera, dtype: object
Id
a    Barcelona
d      Sevilla
Name: Ciudades con dos equipos en primera, dtype: object

In [13]:
# slicing
print(football_cities[:'c']) # incluye ambos extremos con el indice semantico
print(football_cities[:2])

Id
a    Barcelona
b       Madrid
c     Valencia
Name: Ciudades con dos equipos en primera, dtype: object
Id
a    Barcelona
b       Madrid
Name: Ciudades con dos equipos en primera, dtype: object

In [14]:
#cast a list
lista = list(football_cities[:'c'])
print(lista)
print(type(lista))

['Barcelona', 'Madrid', 'Valencia']
<class 'list'>

In [15]:
type(football_cities[:'c'])

pandas.core.series.Series

In [16]:
#cast a ndarray
import numpy as np
cities = np.array(football_cities[:'c'])
print(cities)
print(type(cities))

['Barcelona' 'Madrid' 'Valencia']
<class 'numpy.ndarray'>

In [17]:
# cas a dictionary
lista = dict(football_cities[:'c'])
print(lista)

{'a': 'Barcelona', 'b': 'Madrid', 'c': 'Valencia'}

In [18]:
# uso de masks para seleccionar
fibonacci = pd.Series([0, 1, 1, 2, 3, 5, 8, 13, 21])
print(fibonacci)
mask = fibonacci > 10
print(mask)
print(fibonacci[mask])
dst = pd.Series([13,21])
print(dst)
dst.equals(fibonacci)
fb = fibonacci[mask]
fb.reset_index(drop=True, inplace=True)
print(fb)
dst.equals(fb)

0     0
1     1
2     1
3     2
4     3
5     5
6     8
7    13
8    21
dtype: int64
0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8     True
dtype: bool
7    13
8    21
dtype: int64
0    13
1    21
dtype: int64
0    13
1    21
dtype: int64

True

In [19]:
# aplicar funciones de numpy a la serie
import numpy as np
print(np.sum(fibonacci))

54

In [20]:
#filtrado con np.where
distances = pd.Series([12.1,np.nan,12.8,76.9,6.1,7.2])
valid_distances = np.where(pd.notnull(distances),distances,2)
print(valid_distances)
print(type(valid_distances))

[12.1  2.  12.8 76.9  6.1  7.2]
<class 'numpy.ndarray'>

### 3.0.1 Iteración

In [23]:
# iterar sobre elementos
for value in fibonacci:
 print('Value: ' + str(value))
# # iterar sobre indices
for index in fibonacci.index:
 print('Index: ' + str(index))

Value: 0
Value: 1
Value: 1
Value: 2
Value: 3
Value: 5
Value: 8
Value: 13
Value: 21
Index: 0
Index: 1
Index: 2
Index: 3
Index: 4
Index: 5
Index: 6
Index: 7
Index: 8

In [25]:
# iterar sobre elementos e índices al mismo tiempo
for index, value in fibonacci.items():
 print('Index: ' + str(index) + ' Value: ' + str(value))

Index: 0 Value: 0
Index: 1 Value: 1
Index: 2 Value: 1
Index: 3 Value: 2
Index: 4 Value: 3
Index: 5 Value: 5
Index: 6 Value: 8
Index: 7 Value: 13
Index: 8 Value: 21

In [27]:
for index, value in zip(fibonacci.index, fibonacci):
 print('Index: ' + str(index) + ' Value: ' + str(value))

Index: 0 Value: 0
Index: 1 Value: 1
Index: 2 Value: 1
Index: 3 Value: 2
Index: 4 Value: 3
Index: 5 Value: 5
Index: 6 Value: 8
Index: 7 Value: 13
Index: 8 Value: 21

### 3.1 Series como diccionarios
* Interpretar el índice como clave
* Acepta operaciones para diccionarios

In [28]:
# crear una serie a partir de un diccionario
serie = pd.Series( { 'Carlos' : 100, 'Marcos': 98} )
print(serie.index)
print(serie.values)
print(serie)
print(type(serie))

Index(['Carlos', 'Marcos'], dtype='object')
[100  98]
Carlos    100
Marcos     98
dtype: int64
<class 'pandas.core.series.Series'>

In [29]:
# añade y elimina elementos a través de índices
serie['Pedro'] = 12
serie['Pedro']=15
del serie['Marcos']
print(serie)

Carlos    100
Pedro      15
dtype: int64

In [34]:
# query una serie
# print(serie['Marcos'])
if 'Marcos' in serie:
 print(serie['Marcos'])
print(serie)

Carlos    100
Pedro      15
dtype: int64

### 3.2 Operaciones entre series

In [35]:
# suma de dos series
# suma de valores con el mismo índice (NaN si no aparece en ambas)
serie1 = pd.Series([10,20,30,40], index=range(4) )
serie2 = pd.Series([1,2,3], index=range(3) )
suma = serie1 + serie2
print(suma)

0    11.0
1    22.0
2    33.0
3     NaN
dtype: float64

In [36]:
# resta de series (similar a la suma)
print(serie1- serie2)

0     9.0
1    18.0
2    27.0
3     NaN
dtype: float64

In [37]:
# operaciones de pre-filtrado
result = serie1 + serie2
result[pd.isnull(result)] = 0 # mask con isnull()
print(result)

0    11.0
1    22.0
2    33.0
3     0.0
dtype: float64

### 3.2.1 Diferencias entre Pandas Series y diccionario

* Diccionario, es una estructura que relaciona las claves y los valores de forma arbitraria.
* Series, estructura de forma estricta listas de valores con listas de índice asignado en la posición.
* Series, es más eficiente para ciertas operaciones que los dicionarios.
* Enlas Series los valores de entrada pueden ser listas o Numpy arrays.
* EnSeries los índices semánticos pueden ser integers o caracteres, en los valores igual.
* Series se podría entender entre una lista y un diccionario Python, pero es de una dimensión.

### 4 DataFrame

* Datos tabulares (filas x columnas)
* Columnas: Series con índices compartidos

In [40]:
# crear un DataFrame a partir de un diccionario de elementos de la misma longitud
diccionario = { "Nombre" : ["Marisa","Laura","Manuel"],
"Edad" : [34,29,12] }

print(diccionario)

# las claves identifican columnas
frame = pd.DataFrame(diccionario)
display(frame)

{'Nombre': ['Marisa', 'Laura', 'Manuel'], 'Edad': [34, 29, 12]}

   Nombre  Edad
0  Marisa    34
1   Laura    29
2  Manuel    12

In [43]:
# crear un DataFrame a partir de un diccionario de elementos de la misma longitud
diccionario = { "Nombre" : ["Marisa","Laura","Manuel"],
"Edad" : [34,29,12] }

# las claves identifican columnas
frame = pd.DataFrame(diccionario, index = ['a', 'b', 'c'])
display(frame)

   Nombre  Edad
a  Marisa    34
b   Laura    29
c  Manuel    12

In [50]:
# además de `index`, el parámetro `columns` especifica el número y orden de las columnas
frame = pd.DataFrame(diccionario, columns = ['Nacionalidad', 'Nombre', 'Edad', 'Profesión', 'Genero'])

display(frame)

  Nacionalidad  Nombre  Edad Profesión Genero
0          NaN  Marisa    34       NaN    NaN
1          NaN   Laura    29       NaN    NaN
2          NaN  Manuel    12       NaN    NaN

In [52]:
# acceso a columnas
nombres = frame['Nombre']
display(nombres)
5
print(type(nombres))
edades = frame['Edad']
display(edades)
print(type(edades))

0    Marisa
1     Laura
2    Manuel
Name: Nombre, dtype: object

<class 'pandas.core.series.Series'>

0    34
1    29
2    12
Name: Edad, dtype: int64

<class 'pandas.core.series.Series'>

In [53]:
#siempre que el nombre de la columna lo permita (espacios, ...)
nombres = frame.Profesion
display(nombres)
type(nombres)

AttributeError: 'DataFrame' object has no attribute 'Profesion'

In [54]:
# acceso al primer nombre del DataFrame frame??
print(frame['Nombre'][0])
print(frame.Nombre[0])
print(nombres[0])

Marisa
Marisa
Marisa

### 4.0.1 Formas de crear un DataFrame

* Con una Serie de pandas
* Lista de diccionarios
* Dicionario de Series de Pandas
* Con un array de Numpy de dos dimensiones
* Con array estructurado de Numpy

### 4.1 Modificar DataFrames

In [56]:
# añadir columnas
diccionario = { "Nombre" : ["Marisa","Laura","Manuel"],
"Edad" : [34,29,12] }
frame = pd.DataFrame(diccionario, columns=['Nacionalidad', 'Nombre',
'Edad','Profesion', 'Direccion'])
frame['Direccion'] = 'Desconocida'
display(frame)

  Nacionalidad  Nombre  Edad Profesion    Direccion
0          NaN  Marisa    34       NaN  Desconocida
1          NaN   Laura    29       NaN  Desconocida
2          NaN  Manuel    12       NaN  Desconocida

In [60]:
lista_direcciones = [
    'Rue 13 del Percebe, 13',
    'Evergreen Terrace, 3',
    'Av de los Rombos, 12'
]

In [61]:
frame['Direccion'] = lista_direcciones
display(frame)

  Nacionalidad  Nombre  Edad Profesion               Direccion
0          NaN  Marisa    34       NaN  Rue 13 del Percebe, 13
1          NaN   Laura    29       NaN    Evergreen Terrace, 3
2          NaN  Manuel    12       NaN    Av de los Rombos, 12

In [62]:
# añadir fila (requiere todos los valores)
user_2 = ['Alemania','Klaus',20, 'none','Desconocida']
frame.loc[3] = user_2
display(frame)

  Nacionalidad  Nombre  Edad Profesion               Direccion
0          NaN  Marisa    34       NaN  Rue 13 del Percebe, 13
1          NaN   Laura    29       NaN    Evergreen Terrace, 3
2          NaN  Manuel    12       NaN    Av de los Rombos, 12
3     Alemania   Klaus    20      none             Desconocida

In [64]:
# eliminar fila (similar a Series)
frame = pd.DataFrame(diccionario,columns=['Nacionalidad', 'Nombre', 'Edad',
'Profesion'])
frame = frame.drop(2) # por qué necesitamos reasignar el frame?
display(frame)
frame.drop('Nombre', axis = 1, inplace = True)
display(frame)

  Nacionalidad  Nombre  Edad Profesion
0          NaN  Marisa    34       NaN
1          NaN   Laura    29       NaN

  Nacionalidad  Edad Profesion
0          NaN    34       NaN
1          NaN    29       NaN

In [65]:
#eliminar columna
del frame['Profesion']
display(frame)

  Nacionalidad  Edad
0          NaN    34
1          NaN    29

In [66]:
# acceder a la traspuesta (como una matriz)
display(frame.T)

                0    1
Nacionalidad  NaN  NaN
Edad           34   29

### 4.2 Iteración

In [70]:
# iteración sobre el DataFrame?
frame = pd.DataFrame(diccionario, columns=['Nacionalidad', 'Nombre', 'Edad',
'Profesion'])
display(frame)
for a in frame:
 print(a) 
print(type(a))

  Nacionalidad  Nombre  Edad Profesion
0          NaN  Marisa    34       NaN
1          NaN   Laura    29       NaN
2          NaN  Manuel    12       NaN

Nacionalidad
Nombre
Edad
Profesion
<class 'str'>

In [71]:
# iteracion sobre filas
for value in frame.values:
 print(value)
print(type(value))

[nan 'Marisa' 34 nan]
[nan 'Laura' 29 nan]
[nan 'Manuel' 12 nan]
<class 'numpy.ndarray'>

In [75]:
# iterar sobre filas y luego sobre cada valor?
for values in frame.values:
 for value in values:
  print(value)

nan
Marisa
34
nan
nan
Laura
29
nan
nan
Manuel
12
nan

### 4.3 Indexación y slicing con DataFrames

In [79]:
d1 = {'ciudad':'Valencia', 'temperatura':10, 'o2':1}
d2 = {'ciudad':'Barcelona', 'temperatura':8}
d3 = {'ciudad':'Valencia', 'temperatura':9}
d4 = {'ciudad':'Madrid', 'temperatura':10, 'humedad':80}
d5 = {'ciudad':'Sevilla', 'temperatura':15, 'humedad':50, 'co2':6}
d6 = {'ciudad':'Valencia', 'temperatura':10, 'humedad':90, 'co2':10}
7
ls_data = [d1, d2, d3, d4, d5, d6] # lista de diccionarios
df_data = pd.DataFrame(ls_data, index = list('abcdef'))
display(df_data)

      ciudad  temperatura   o2  humedad   co2
a   Valencia           10  1.0      NaN   NaN
b  Barcelona            8  NaN      NaN   NaN
c   Valencia            9  NaN      NaN   NaN
d     Madrid           10  NaN     80.0   NaN
e    Sevilla           15  NaN     50.0   6.0
f   Valencia           10  NaN     90.0  10.0

In [80]:
# Acceso a un valor concreto por indice posicional [row, col]
print(df_data.iloc[1,1])
# Acceso a todos los valores hasta un índice por enteros
display(df_data.iloc[:3,:4])
# Acceso a datos de manera explícita, indice semantico (se incluyen)
display(df_data.loc['a', 'temperatura'])
display(df_data.loc[:'c', :'o2'])
display(df_data.loc[:'c', 'temperatura':'o2'])
display(df_data.loc[:, ['ciudad','o2']])

8

      ciudad  temperatura   o2  humedad
a   Valencia           10  1.0      NaN
b  Barcelona            8  NaN      NaN
c   Valencia            9  NaN      NaN

np.int64(10)

      ciudad  temperatura   o2
a   Valencia           10  1.0
b  Barcelona            8  NaN
c   Valencia            9  NaN

   temperatura   o2
a           10  1.0
b            8  NaN
c            9  NaN

      ciudad   o2
a   Valencia  1.0
b  Barcelona  NaN
c   Valencia  NaN
d     Madrid  NaN
e    Sevilla  NaN
f   Valencia  NaN

In [81]:
# indexación con nombre de columna (por columnas)
print(df_data['ciudad']) #--> Series
display(df_data[['ciudad', 'o2']])

a     Valencia
b    Barcelona
c     Valencia
d       Madrid
e      Sevilla
f     Valencia
Name: ciudad, dtype: object

      ciudad   o2
a   Valencia  1.0
b  Barcelona  NaN
c   Valencia  NaN
d     Madrid  NaN
e    Sevilla  NaN
f   Valencia  NaN

In [83]:
# indexación con índice posicional (no permitido!). Esto busca columna.
df_data.iloc[0]

ciudad         Valencia
temperatura          10
o2                  1.0
humedad             NaN
co2                 NaN
Name: a, dtype: object

In [84]:
# indexar por posición con 'iloc'
print(df_data.iloc[0]) #--> Series de la primera fila (qué marca los índices)

ciudad         Valencia
temperatura          10
o2                  1.0
humedad             NaN
co2                 NaN
Name: a, dtype: object

In [85]:
# indexar semántico con 'loc'
df_data.loc['a'] #--> Series de la fila con índice 'a'

ciudad         Valencia
temperatura          10
o2                  1.0
humedad             NaN
co2                 NaN
Name: a, dtype: object

In [86]:
# indexar semántico con 'loc'
df_data.loc[:'b'] #--> DataFrame de la fila con índice 'a' y 'b'

      ciudad  temperatura   o2  humedad  co2
a   Valencia           10  1.0      NaN  NaN
b  Barcelona            8  NaN      NaN  NaN

In [87]:
df_data.loc[:'b'].loc[:,["o2", "humedad"]] # slicing anidado

    o2  humedad
a  1.0      NaN
b  NaN      NaN

In [89]:
# si se modifica una porcion del dataframe se modifica el original (referencia)
display(df_data)

serie = df_data.loc['a']
print(serie)

serie.iloc[2] = 3000  # setting with copy warning!!!
display(df_data)

# copiar data frame
df_2 = df_data.loc['a'].copy()

      ciudad  temperatura   o2  humedad   co2
a   Valencia           10  1.0      NaN   NaN
b  Barcelona            8  NaN      NaN   NaN
c   Valencia            9  NaN      NaN   NaN
d     Madrid           10  NaN     80.0   NaN
e    Sevilla           15  NaN     50.0   6.0
f   Valencia           10  NaN     90.0  10.0

ciudad         Valencia
temperatura          10
o2                  1.0
humedad             NaN
co2                 NaN
Name: a, dtype: object

C:\Users\santi\AppData\Local\Temp\ipykernel_8888\3731434400.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  serie.iloc[2] = 3000  # setting with copy warning!!!

      ciudad  temperatura   o2  humedad   co2
a   Valencia           10  1.0      NaN   NaN
b  Barcelona            8  NaN      NaN   NaN
c   Valencia            9  NaN      NaN   NaN
d     Madrid           10  NaN     80.0   NaN
e    Sevilla           15  NaN     50.0   6.0
f   Valencia           10  NaN     90.0  10.0

In [93]:
# ambos aceptan `axis` como argumento
# df_data.iloc(axis=1)[0] #--> todos los valores asignados a la primera columna
# columna 'ciudad'
df_data.loc(axis=1)['ciudad']  #--> equivalente frame['ciudad']

a     Valencia
b    Barcelona
c     Valencia
d       Madrid
e      Sevilla
f     Valencia
Name: ciudad, dtype: object

In [95]:
# qué problema puede tener este fragmento?
frame = pd.DataFrame({"Name" : ['Carlos','Pedro'], "Age" : [34,22]},
index=[1,0])
display(frame)

     Name  Age
1  Carlos   34
0   Pedro   22

In [96]:
# por defecto, pandas interpreta índice posicional--> error en frames
# cuando hay posible ambigüedad, utilizar loc y iloc
print('Primera fila\n')
print(frame.iloc[0])
print('\nElemento con index 0\n')
print(frame.loc[0])

Primera fila

Name    Carlos
Age         34
Name: 1, dtype: object

Elemento con index 0

Name    Pedro
Age        22
Name: 0, dtype: object

### 4.4 Objeto Index de Pandas

In [97]:
# Contrucción de índices
ind = pd.Index([2, 3, 5, 23, 26])
# recuperar datos
print(ind[3])
print(ind[::2])

23
Index([2, 5, 26], dtype='int64')

In [99]:
# usar un objeto index al crear dataframe
frame = pd.DataFrame({"Name" : ['Carlos','Pedro', 'Manolo', 'Luis', 'Alberto'],
"Age" : [34,22,15,55,23]}, index=ind)
display(frame)

       Name  Age
2    Carlos   34
3     Pedro   22
5    Manolo   15
23     Luis   55
26  Alberto   23

In [100]:
# Son inmutables! No se modifican los datos.
ind[3] = 8

TypeError: Index does not support mutable operations

In [4]:
import pandas as pd

# definir index (porque el ejercicio anterior dependía de esto)
index = ['a', 'b', 'c', 'd', 'e']

# change index column
frame = pd.DataFrame(
    {"Name": ['Carlos','Pedro','Manolo','Luis','Ana'],
     "Age": [34,22,15,55,23]},
    index=index
)

display(frame)

frame.set_index("Age", inplace=True)
display(frame)

     Name  Age
a  Carlos   34
b   Pedro   22
c  Manolo   15
d    Luis   55
e     Ana   23

       Name
Age
34   Carlos
22    Pedro
15   Manolo
55     Luis
23      Ana

### 4.5 Slicing

In [6]:
# slice por filas
d_and_d_characters = {'Name' : ['bundenth','theorin','barlok'], 'Strength' :
[10,12,19], 'Wisdom' : [20,13,6]}
character_data = pd.DataFrame(d_and_d_characters, index=['a','b','c'])
display(character_data)
display(character_data[:-1])
display(character_data[1:2])

       Name  Strength  Wisdom
a  bundenth        10      20
b   theorin        12      13
c    barlok        19       6

       Name  Strength  Wisdom
a  bundenth        10      20
b   theorin        12      13

      Name  Strength  Wisdom
b  theorin        12      13

In [7]:
# slicing para columnas
display(character_data[['Name','Wisdom']])

       Name  Wisdom
a  bundenth      20
b   theorin      13
c    barlok       6

In [8]:
#slicing con 'loc' e 'iloc'
display(character_data.iloc[1:])
display(character_data.loc[:'b','Name':'Strength'])

      Name  Strength  Wisdom
b  theorin        12      13
c   barlok        19       6

       Name  Strength
a  bundenth        10
b   theorin        12

¿Cómo filtrar filas y columnas? Por ejemplo, para todos los personajes, obtener ‘Name’ y ‘Strength’

In [9]:
# usando 'loc' para hacer slicing
display(character_data.loc[:,'Name':'Strength'])

       Name  Strength
a  bundenth        10
b   theorin        12
c    barlok        19

In [10]:
# usando 'loc' para buscar específicamente filas y columnas
display(character_data.loc[ ['a','c'], ['Name','Wisdom'] ])

       Name  Wisdom
a  bundenth      20
c    barlok       6

In [11]:
# lo mismo con 'iloc'?
display(character_data.iloc[[0,2],[0,2]])
display(character_data.iloc[[0,-1],[0,-1]])

       Name  Wisdom
a  bundenth      20
c    barlok       6

       Name  Wisdom
a  bundenth      20
c    barlok       6

In [13]:
# lista de los personajes con el atributo Strength > 11
display(character_data.loc[character_data['Strength'] > 11, ['Name',
'Strength']])

      Name  Strength
b  theorin        12
c   barlok        19

In [15]:
# listar los personajes con Strength > 15 o Wisdom > 15
display(character_data.loc[(character_data['Strength'] > 15) |
(character_data['Wisdom'] > 15)])

       Name  Strength  Wisdom
a  bundenth        10      20
c    barlok        19       6

### 5 Cargar y guardar datos en pandas

In [16]:
# Guardar a csv
import os
ruta = os.path.join("res" ,"o_d_d_characters.csv")
#character_data.to_csv(ruta, sep=';') # sep por defecto: ','

In [17]:
loaded = pd.read_csv(ruta, sep=';')
display(loaded)

  Unnamed: 0      Name  Strength  Wisdom
0          a  bundenth        10      20
1          b   theorin        12      13
2          c    barlok        19       6

In [19]:
ruta = os.path.join("res","titanic.csv")

In [20]:
titanic = pd.read_csv(ruta, sep=',')
display(titanic)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [21]:
loaded = pd.read_csv(ruta, sep=',', index_col = 0)
display(loaded)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

otros argumentos to_csv()

* na_rep=‘string’–> representar valores NaN en el archivo csv

otros argumentos read_csv()

* na_values=‘string

Pandas también ofrece funciones para leer/guardar a otros formatos estándares: JSON, HDF5 o
Excel en su API

### 6 Ejemplo práctico en pandas

* MovieLens dataset
* Reviews de películas
* 1millón de entradas
* Datos demográficos de usuarios

In [25]:
import numpy as np
import pandas as pd
import zipfile # para descomprimir archivos zip
import urllib.request # para descargar de URL
import os
# descargar MovieLens dataset
url = 'http://files.grouplens.org/datasets/movielens/ml-1m.zip'
ruta = os.path.join("res", "ml-1m.zip")
urllib.request.urlretrieve(url, ruta)

('res\\ml-1m.zip', <http.client.HTTPMessage at 0x2d3ea6d1940>)

In [33]:
import os
import zipfile

# definir ruta del zip (debe estar en la misma carpeta del notebook)
ruta = "archivo.zip"   # ⚠️ cambia por el nombre real

# descomprimiendo archivo zip
ruta_ext = os.path.join("res")

with zipfile.ZipFile(ruta, 'r') as z:
    print("Extracting all files...")
    z.extractall(ruta_ext)  # destino
    print("Done!")

# take a look at readme y revisar formatos

FileNotFoundError: [Errno 2] No such file or directory: 'archivo.zip'

In [34]:
ruta_users = os.path.join("res", "ml-1m", "users.dat")
11
users_dataset = pd.read_csv(ruta_users, sep='::', index_col=0, engine='python')
display(users_dataset)

      F  1.1  10  48067
1
2     M   56  16  70072
3     M   25  15  55117
4     M   45   7  02460
5     M   25  20  55455
6     F   50   9  55117
...  ..  ...  ..    ...
6036  F   25  15  32603
6037  F   45   1  76006
6038  F   56   1  14706
6039  F   45   0  01060
6040  M   25   6  11106

[6039 rows x 4 columns]

In [2]:
# Varios problemas
# sin cabecera! primer valor se ha perdido
# las columnas no tienen nombres
pd.read_csv?

Object `pd.read_csv` not found.

In [4]:
import pandas as pd

# especificar nombres, cargar sin cabecera
users_dataset = pd.read_csv(ruta_users, sep="::", index_col=0,
                            header=None, names=['UserID','Gender','Age','Occupation','Zip-code'],
                            engine='python')

display(users_dataset)

NameError: name 'ruta_users' is not defined